name: ECONOMY
version: '1.0 beta'
main: sciencemj.shop.Ecnm
api-version: 1.19
authors: [ sciencemj ]
description: economy plugin for mc
website: https://github.com/sciencemj

commands:
  money:
    description: manage players money status
    usage: /money <player> <set|add|get> <amount>
  store:
    description: manage stor
    usage: /store <set>