name: Shop
version: '${version}'
main: sciencemj.shop.Ecnm
api-version: 1.19
authors: [ sciencemj ]
description: economic plugin for mc
website: https://github.com/sciencemj

commands:
  money:
    description: manage players money status
    usage: /money <player> <set|add|get> <amount>